connect : connect.cpp 
	g++ connect.cpp -o connect.o

getascii : getascii.cpp
	g++ getascii.cpp -o getascii.o


ayt : test_AYT.cpp
	g++ test_AYT.cpp -o ayt.o

formfeed : ff.cpp
	g++ ff.cpp -o formfeed

back_to_first_line : back_to_first_line.cpp
	g++ back_to_first_line.cpp -o back_to_first_line.o

ansi : ansi.cpp
	g++ ansi.cpp -o ansi.o
clean :
	rm -f *.o
