#define BBS_ERROR_NOT_CONNECTED -1
#define BBS_ERROR_SUCCESS 0
#define BBS_ERROR_INTERNAL_ERROR -2
#define BBS_ERROR_FUNCTION_SOCKET_FAILED -3
#define BBS_ERROR_FUNCTION_GETHOSTENT_FAILED -4
#define BBS_ERROR_FUNCITON_CONNECT_FAILED -5

